#!/usr/bin/env python3
"""One-off script: translate Chinese comments/docstrings in backend Python source."""

from __future__ import annotations

import re
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent

SKIP_FILES = {
    BACKEND / "config" / "disclaimers.py",
    BACKEND / "scripts" / "translate_comments.py",
}

SKIP_DIRS = {"tests", "__pycache__", ".pytest_cache"}

# Direct phrase replacements (longest first)
PHRASES: list[tuple[str, str]] = [
    # Module headers (bilingual second line removal handled separately)
    ("API装饰器 - 统一的错误处理和通用模式", ""),
    ("安全响应头中间件 - 为响应添加安全头", ""),
    ("权限中间件 - 基于角色的访问控制依赖", ""),
    ("性能监控中间件 - 追踪 API 性能指标", ""),
    ("依赖注入 - 统一的依赖注入", ""),
    ("数据库配置 - 与业务逻辑分离", ""),
    ("Authentication Middleware - 认证中间件", "Authentication Middleware"),
    ("Emergency API Routes - 紧急情况API路由", "Emergency API Routes"),
    ("Knowledge Base API Routes - 知识库API路由", "Knowledge Base API Routes"),
    ("Notification API Routes - 通知API路由", "Notification API Routes"),
    ("Family Member Management API Routes - 家庭成员管理API路由", "Family Member Management API Routes"),
    ("Family Participation API Routes - 家庭成员参与API路由", "Family Participation API Routes"),
    ("Summary API Routes - 信息摘要API路由", "Summary API Routes"),
    ("Schedule Management API Routes - 日程管理API路由", "Schedule Management API Routes"),
    ("Emotion Logging API Routes - 情绪日志API路由", "Emotion Logging API Routes"),
    ("Task Management API Routes - 任务管理API路由", "Task Management API Routes"),
    ("Night Mode API Routes - 夜间模式API路由", "Night Mode API Routes"),
    ("Emergency Service - 紧急情况服务", "Emergency Service"),
    ("Night Mode Service - 夜间模式服务", "Night Mode Service"),
    ("Notification Service - 通知服务", "Notification Service"),
    ("Reminder Service - 提醒服务", "Reminder Service"),
    ("Customer Summary Service - 客户信息摘要服务", "Customer Summary Service"),
    ("RAG服务 - 检索增强生成服务", "RAG Service - Retrieval-Augmented Generation"),
    ("反馈路由 - 用户反馈和建议", "Feedback Routes - User feedback and suggestions"),
    ("分析路由 - 用户行为追踪", "Analytics Routes - User behavior tracking"),
    ("支持路由 - 工单系统", "Support Routes - Ticket system"),
    ("监控路由 - 系统监控端点", "Monitoring Routes - System monitoring endpoints"),
    ("支付路由 - 支付和订阅管理", "Payment Routes - Payment and subscription management"),
    ("API 密钥管理路由", "API Key Management Routes"),
    ("数据导出路由 - GDPR 合规的数据导出", "Data Export Routes - GDPR-compliant data export"),
    ("数据删除路由 - 账户删除（GDPR 合规）", "Data Deletion Routes - Account deletion (GDPR compliant)"),
    ("帮助中心路由 - 帮助文章和常见问题", "Help Center Routes - Help articles and FAQs"),
    ("图片优化 API 路由", "Image Optimization API Routes"),
    ("语音API路由", "Voice API Routes"),
    ("API 版本 1 - 版本 1 的 API 路由", "API Version 1 Routes"),
    ("Web Vitals API 路由 - 历史数据和 analytics", "Web Vitals API Routes - Historical data and analytics"),
    ("CDN API 路由", "CDN API Routes"),
    ("增强的活动API路由 - 高级功能", "Enhanced Activity API Routes - Advanced features"),
    ("处理紧急情况记录、AI引导、简短汇报生成", "Handles emergency records, AI guidance, and brief report generation"),
    ("管理夜间模式配置", "Manages night mode configuration"),
    ("AI生成温和语气的提醒", "AI-generated reminders with a gentle tone"),
    ("智能整理呈现老人信息，避免重复询问", "Intelligently organizes elder information to avoid repeated questions"),
    ("统一的API端点错误处理装饰器", "Unified error-handling decorator for API endpoints"),
    ("为所有响应添加安全头的中间件", "Middleware that adds security headers to all responses"),
    # Common docstrings
    ("用户注册", "Register a new user"),
    ("用户登录", "User login"),
    ("注册设备", "Register a device"),
    ("获取用户的所有设备", "Get all devices for the user"),
    ("获取当前用户信息", "Get current user information"),
    ("添加文档请求", "Add document request"),
    ("RAG问答请求", "RAG Q&A request"),
    ("创建对话请求", "Create conversation request"),
    ("搜索文档", "Search documents"),
    ("创建新对话（用于多轮对话）", "Create a new conversation (for multi-turn dialogue)"),
    ("RAG问答（支持多轮对话）", "RAG Q&A (supports multi-turn dialogue)"),
    ("获取官方来源列表", "Get official source list"),
    ("记录紧急情况请求", "Record emergency request"),
    ("获取AI引导请求", "Get AI guidance request"),
    ("记录紧急情况", "Record an emergency"),
    ("获取AI紧急引导", "Get AI emergency guidance"),
    ("获取紧急情况历史记录", "Get emergency history"),
    ("创建反馈请求", "Create feedback request"),
    ("更新反馈状态请求", "Update feedback status request"),
    ("添加评论请求", "Add comment request"),
    ("满意度调查请求", "Satisfaction survey request"),
    ("创建反馈（支持匿名）", "Create feedback (anonymous supported)"),
    ("获取反馈列表（用户只能看到自己的）", "Get feedback list (users see only their own)"),
    ("获取单个反馈", "Get a single feedback item"),
    ("更新反馈状态（管理员）", "Update feedback status (admin)"),
    ("添加评论", "Add a comment"),
    ("提交满意度调查", "Submit satisfaction survey"),
    ("追踪事件请求", "Track event request"),
    ("追踪用户事件", "Track a user event"),
    ("获取事件统计", "Get event statistics"),
    ("获取用户留存分析", "Get user retention analysis"),
    ("获取功能使用统计", "Get feature usage statistics"),
    ("获取转化漏斗分析", "Get conversion funnel analysis"),
    ("创建工单请求", "Create ticket request"),
    ("更新工单请求", "Update ticket request"),
    ("添加消息请求", "Add message request"),
    ("创建支持工单", "Create a support ticket"),
    ("获取工单列表", "Get ticket list"),
    ("获取单个工单", "Get a single ticket"),
    ("更新工单（管理员/支持人员）", "Update ticket (admin/support staff)"),
    ("添加工单消息", "Add ticket message"),
    ("获取系统资源使用情况", "Get system resource usage"),
    ("获取API性能指标", "Get API performance metrics"),
    ("获取错误率统计", "Get error rate statistics"),
    ("获取用户活跃度统计", "Get user activity statistics"),
    ("获取综合监控数据", "Get aggregated monitoring data"),
    ("创建订阅请求", "Create subscription request"),
    ("取消订阅请求", "Cancel subscription request"),
    ("创建订阅", "Create subscription"),
    ("获取当前订阅", "Get current subscription"),
    ("取消订阅", "Cancel subscription"),
    ("获取支付历史", "Get payment history"),
    ("创建 API 密钥请求", "Create API key request"),
    ("更新 API 密钥请求", "Update API key request"),
    ("创建新的 API 密钥", "Create a new API key"),
    ("获取用户的 API 密钥列表", "Get user's API key list"),
    ("更新 API 密钥设置", "Update API key settings"),
    ("撤销（停用）API 密钥", "Revoke (deactivate) API key"),
    ("删除账户请求", "Delete account request"),
    ("获取账户删除摘要（将删除哪些数据）", "Get account deletion summary (what data will be removed)"),
    ("请求账户删除（创建删除请求）", "Request account deletion (create deletion request)"),
    ("反馈请求", "Feedback request"),
    ("获取帮助文章列表", "Get help article list"),
    ("获取单个帮助文章", "Get a single help article"),
    ("获取常见问题列表", "Get FAQ list"),
    ("获取单个常见问题", "Get a single FAQ"),
    ("提交反馈", "Submit feedback"),
    ("获取所有分类", "Get all categories"),
    ("搜索帮助内容", "Search help content"),
    ("发送通知请求", "Send notification request"),
    ("发送家庭成员通知请求", "Send family member notification request"),
    ("发送通知", "Send notification"),
    ("发送通知给家庭成员", "Send notification to family members"),
    ("获取通知列表", "Get notification list"),
    ("标记通知为已读", "Mark notification as read"),
    ("标记所有通知为已读", "Mark all notifications as read"),
    ("添加家庭成员请求", "Add family member request"),
    ("更新家庭成员请求", "Update family member request"),
    ("添加家庭成员", "Add family member"),
    ("获取家庭成员列表", "Get family member list"),
    ("获取单个家庭成员", "Get a single family member"),
    ("更新家庭成员信息", "Update family member information"),
    ("删除家庭成员", "Delete family member"),
    ("提交反馈请求", "Submit feedback request"),
    ("添加家庭成员到任务", "Add family member to task"),
    ("添加家庭成员到日程", "Add family member to schedule"),
    ("获取家庭成员参与的任务", "Get tasks with family member participation"),
    ("获取家庭成员参与的日程", "Get schedules with family member participation"),
    ("提交家庭成员反馈", "Submit family member feedback"),
    ("获取反馈列表", "Get feedback list"),
    ("获取反馈摘要", "Get feedback summary"),
    ("记录信息变化请求", "Record information change request"),
    ("获取客户信息摘要", "Get customer information summary"),
    ("获取信息卡片数据（用于可视化呈现）", "Get information card data (for visualization)"),
    ("获取信息变化列表", "Get information change list"),
    ("记录信息变化", "Record information change"),
    ("创建日程请求", "Create schedule request"),
    ("更新日程请求", "Update schedule request"),
    ("创建日程", "Create schedule"),
    ("获取日程列表", "Get schedule list"),
    ("获取日历视图数据", "Get calendar view data"),
    ("获取单个日程", "Get a single schedule"),
    ("更新日程", "Update schedule"),
    ("删除日程", "Delete schedule"),
    ("创建客户请求", "Create customer request"),
    ("创建照护关系请求", "Create care relationship request"),
    ("个性化数据请求", "Personalization data request"),
    ("行为日志请求", "Behavior log request"),
    ("互动记录请求", "Interaction record request"),
    ("批量创建客户请求", "Batch create customers request"),
    ("批量更新客户请求", "Batch update customers request"),
    ("创建客户", "Create customer"),
    ("获取客户信息", "Get customer information"),
    ("更新客户信息", "Update customer information"),
    ("创建照护关系", "Create care relationship"),
    ("获取照护关系列表", "Get care relationship list"),
    ("保存个性化数据", "Save personalization data"),
    ("获取个性化数据", "Get personalization data"),
    ("记录行为日志", "Record behavior log"),
    ("获取行为模式分析", "Get behavior pattern analysis"),
    ("记录看护者和老人的互动", "Record caregiver-elder interaction"),
    ("获取互动历史", "Get interaction history"),
    ("批量创建客户（优化版本，使用批量插入）", "Batch create customers (optimized with bulk insert)"),
    ("批量更新客户", "Batch update customers"),
    ("记录情绪请求", "Record emotion request"),
    ("正向反馈请求", "Positive feedback request"),
    ("压力检测请求", "Stress detection request"),
    ("记录情绪", "Record emotion"),
    ("获取情绪历史", "Get emotion history"),
    ("获取情绪分析", "Get emotion analysis"),
    ("生成正向反馈", "Generate positive feedback"),
    ("检测压力信号", "Detect stress signals"),
    ("创建任务请求", "Create task request"),
    ("更新任务请求", "Update task request"),
    ("完成任务请求", "Complete task request"),
    ("创建任务", "Create task"),
    ("获取任务列表", "Get task list"),
    ("获取单个任务", "Get a single task"),
    ("更新任务", "Update task"),
    ("完成任务", "Complete task"),
    ("获取任务进度可视化数据", "Get task progress visualization data"),
    ("获取每日任务完成情况总结", "Get daily task completion summary"),
    ("更新夜间模式配置请求", "Update night mode config request"),
    ("获取夜间模式配置", "Get night mode configuration"),
    ("更新夜间模式配置", "Update night mode configuration"),
    ("检查夜间模式是否激活", "Check whether night mode is active"),
    ("同步数据请求", "Sync data request"),
    ("完整数据同步", "Full data sync"),
    ("同步用户配置", "Sync user configuration"),
    ("同步活动记录", "Sync activity records"),
    ("同步翻译历史", "Sync translation history"),
    ("获取同步状态", "Get sync status"),
    ("优化选项", "Optimization options"),
    ("批量优化请求", "Batch optimization request"),
    ("上传图片到存储服务", "Upload image to storage service"),
    ("优化单个图片", "Optimize a single image"),
    ("批量优化图片（支持任务队列）", "Batch optimize images (supports task queue)"),
    ("批量压缩图片", "Batch compress images"),
    ("批量转换为 WebP 格式", "Batch convert to WebP format"),
    ("批量调整图片尺寸", "Batch resize images"),
    ("获取优化任务状态", "Get optimization task status"),
    ("转换图片为 WebP 格式", "Convert image to WebP format"),
    ("获取图片信息", "Get image information"),
    ("文字转语音请求", "Text-to-speech request"),
    ("语音转文字", "Speech-to-text"),
    ("文字转语音", "Text-to-speech"),
    ("保存语音笔记", "Save voice note"),
    ("Web Vitals 数据模型", "Web Vitals data model"),
    ("CDN URL 请求", "CDN URL request"),
    ("批量 CDN URL 请求", "Batch CDN URL request"),
    ("获取 CDN 配置信息", "Get CDN configuration"),
    ("获取单个资源的 CDN URL", "Get CDN URL for a single resource"),
    ("批量获取 CDN URL", "Batch get CDN URLs"),
    ("通过查询参数获取 CDN URL", "Get CDN URL via query parameters"),
    ("创建自定义活动请求", "Create custom activity request"),
    ("活动定制请求", "Activity customization request"),
    ("活动计划请求", "Activity plan request"),
    ("活动效果追踪请求", "Activity effectiveness tracking request"),
    ("分享活动请求", "Share activity request"),
    ("协同设计请求", "Collaborative design request"),
    ("家属参与请求", "Family participation request"),
    ("创建自定义活动", "Create custom activity"),
    ("从模板定制活动", "Customize activity from template"),
    ("创建活动计划", "Create activity plan"),
    ("获取活动计划列表", "Get activity plan list"),
    ("追踪活动效果", "Track activity effectiveness"),
    ("获取活动效果分析", "Get activity effectiveness analysis"),
    ("分享活动到社区", "Share activity to community"),
    ("获取社区分享的活动", "Get community-shared activities"),
    ("协同设计活动", "Collaboratively design activity"),
    ("添加家属参与", "Add family participation"),
    ("获取家属参与信息", "Get family participation info"),
    ("上传活动图片", "Upload activity image"),
    ("上传活动视频", "Upload activity video"),
    ("机构创建/更新请求模型", "Organization create/update request model"),
    ("创建新机构", "Create new organization"),
    ("获取机构信息", "Get organization information"),
    ("更新机构信息", "Update organization information"),
    ("获取机构下的所有用户", "Get all users in organization"),
    ("获取机构使用统计", "Get organization usage statistics"),
    ("老人信息模型（用于活动推荐）", "Elder info model (for activity recommendations)"),
    ("获取性能指标", "Get performance metrics"),
    ("获取慢查询列表", "Get slow query list"),
    ("获取查询优化报告", "Get query optimization report"),
    ("分析特定查询的优化建议", "Analyze optimization suggestions for a specific query"),
    ("查询重写请求", "Query rewrite request"),
    ("重写查询以应用优化", "Rewrite query to apply optimizations"),
    ("自动优化查询（分析 + 重写）", "Auto-optimize query (analyze + rewrite)"),
    ("获取当前 AI 提供商信息", "Get current AI provider information"),
    ("获取支持的语言列表", "Get supported language list"),
    ("获取照护常用术语（已迁移到 /api/care-terms）", "Get common care terms (migrated to /api/care-terms)"),
    ("获取用户个人配置", "Get user personal configuration"),
    ("更新用户个人配置", "Update user personal configuration"),
    ("获取用户翻译历史", "Get user translation history"),
    ("紧急情况服务", "Emergency service"),
    ("夜间模式服务", "Night mode service"),
    ("通知服务", "Notification service"),
    ("提醒服务", "Reminder service"),
    ("客户信息摘要服务", "Customer summary service"),
    ("RAG服务 - 检索增强生成", "RAG service - retrieval-augmented generation"),
    # Field descriptions
    ("文档类型：medical（与健康/医疗相关的参考信息，仅供照护沟通与记录，不构成医疗建议）, diet, care_guide",
     "Document type: medical (health/medical reference for care communication and records, not medical advice), diet, care_guide"),
    ("紧急类型：health, emotional, behavioral", "Emergency type: health, emotional, behavioral"),
    ("严重程度：low, medium, high", "Severity: low, medium, high"),
    ("是否生成AI引导", "Whether to generate AI guidance"),
    ("是否生成简短汇报", "Whether to generate a brief report"),
    ("接收者类型：caregiver, elder, family_member", "Recipient type: caregiver, elder, family_member"),
    ("通知类型：task_reminder, schedule_reminder, emergency等", "Notification type: task_reminder, schedule_reminder, emergency, etc."),
    ("发送方式：push, email, sms, in_app", "Delivery method: push, email, sms, in_app"),
    ("接收者ID（默认当前用户）", "Recipient ID (defaults to current user)"),
    ("关系：son, daughter, spouse等", "Relationship: son, daughter, spouse, etc."),
    ("老人ID", "Elder ID"),
    ("家庭成员ID", "Family member ID"),
    ("反馈类型：task, schedule, activity, general", "Feedback type: task, schedule, activity, general"),
    ("反馈内容", "Feedback content"),
    ("关联任务ID", "Related task ID"),
    ("关联日程ID", "Related schedule ID"),
    ("关联活动ID", "Related activity ID"),
    ("评分（1-5）", "Rating (1-5)"),
    ("开始日期（ISO格式）", "Start date (ISO format)"),
    ("结束日期（ISO格式）", "End date (ISO format)"),
    ("客户ID", "Customer ID"),
    ("字段名", "Field name"),
    ("变化类型：created, updated, deleted", "Change type: created, updated, deleted"),
    ("变化分类", "Change category"),
    ("摘要类型：full, health, preferences, activities", "Summary type: full, health, preferences, activities"),
    ("是否强制重新生成", "Whether to force regeneration"),
    ("起始时间（ISO格式）", "Start time (ISO format)"),
    ("日程类型：medication, exercise, appointment, activity", "Schedule type: medication, exercise, appointment, activity"),
    ("重复模式：daily, weekly, monthly, custom, none", "Recurrence: daily, weekly, monthly, custom, none"),
    ("用户类型：elder, caregiver", "User type: elder, caregiver"),
    ("情绪分数：1-5分", "Emotion score: 1-5"),
    ("情绪类型：happy, sad, anxious, calm等", "Emotion type: happy, sad, anxious, calm, etc."),
    ("用户ID", "User ID"),
    ("分析天数", "Number of days to analyze"),
    ("任务类型：medication, exercise, appointment, custom", "Task type: medication, exercise, appointment, custom"),
    ("优先级：low, medium, high", "Priority: low, medium, high"),
    ("日期（ISO格式，默认为今天）", "Date (ISO format, defaults to today)"),
    ("亮度：low, medium, high", "Brightness: low, medium, high"),
    ("开始时间（HH:MM格式）", "Start time (HH:MM format)"),
    ("结束时间（HH:MM格式）", "End time (HH:MM format)"),
    ("声音类型：gentle, calm, silent", "Sound type: gentle, calm, silent"),
    ("音量（0-100）", "Volume (0-100)"),
    ("字体大小：small, medium, large, extra_large", "Font size: small, medium, large, extra_large"),
    ("配色方案：dark, dim, custom", "Color scheme: dark, dim, custom"),
    ("搜索查询", "Search query"),
    ("标签（逗号分隔）", "Tags (comma-separated)"),
    ("查询天数", "Number of days to query"),
    ("返回数量", "Number of results to return"),
    ("资源路径", "Resource path"),
    ("版本号（用于缓存清除）", "Version number (for cache busting)"),
    # Inline comments
    ("解析日期", "Parse dates"),
    ("解析时间", "Parse datetime"),
    ("解析截止时间", "Parse due datetime"),
    ("输入验证", "Input validation"),
    ("验证输入", "Validate input"),
    ("清理输入", "Sanitize input"),
    ("验证反馈类型", "Validate feedback type"),
    ("验证变化类型", "Validate change type"),
    ("验证用户ID（只能记录自己或关联老人的情绪）", "Validate user ID (may only record self or linked elder)"),
    ("如果没有指定接收者ID，使用当前用户", "Default recipient ID to current user when not specified"),
    ("是否跳过错误继续处理", "Whether to skip errors and continue processing"),
    ("转换 Pydantic 模型为字典", "Convert Pydantic model to dict"),
    ("包含elder_id, doc_type, category等", "Includes elder_id, doc_type, category, etc."),
    ("对话ID（用于多轮对话）", "Conversation ID (for multi-turn dialogue)"),
    ("事件名称", "Event name"),
    ("None = 永不过期", "None = never expires"),
    ("定制内容", "Customization content"),
    ("设计内容", "Design content"),
    ("关系：子女、配偶等", "Relationship: child, spouse, etc."),
    ("兴趣：[\"手工\", \"音乐\", \"运动\"]", 'Interests: e.g. ["crafts", "music", "exercise"]'),
    ("能力：[\"可以坐立\", \"可以动手\"]", 'Abilities: e.g. ["can sit", "can use hands"]'),
    ("健康状况：[\"认知症\", \"行动不便\"]", 'Health conditions: e.g. ["dementia", "limited mobility"]'),
    ("如果为空，创建新活动", "If empty, create a new activity"),
    ("根据环境设置不同的CSP", "Set CSP based on environment"),
    ("生产环境：严格CSP", "Production: strict CSP"),
    ("开发环境：宽松CSP（允许localhost）", "Development: relaxed CSP (allows localhost)"),
    ("防止MIME类型嗅探", "Prevent MIME type sniffing"),
    ("防止点击劫持", "Prevent clickjacking"),
    ("XSS保护（旧版浏览器）", "XSS protection (legacy browsers)"),
    ("控制referrer信息", "Control referrer information"),
    ("控制浏览器功能", "Control browser features"),
    ("仅在生产环境HTTPS时启用", "Enabled only in production over HTTPS"),
    ("注意：只有在HTTPS时才设置HSTS", "Note: set HSTS only when served over HTTPS"),
    ("验证参数", "Validate parameters"),
    ("生成AI引导（如果启用）", "Generate AI guidance if enabled"),
    ("生成语音引导（如果启用）", "Generate voice guidance if enabled"),
    ("生成简短汇报（如果启用）", "Generate brief report if enabled"),
    ("创建记录", "Create record"),
    ("处理异步/同步调用", "Handle async/sync invocation"),
    ("较低温度，更稳定", "Lower temperature for more stable output"),
    ("尝试解析JSON", "Try to parse JSON"),
    ("提取JSON部分", "Extract JSON portion"),
    ("如果不是JSON格式，使用备用方案", "If not JSON, use fallback"),
    ("JSON解析失败，使用备用方案", "JSON parse failed, use fallback"),
    ("使用备用引导", "Use fallback guidance"),
    ("使用TTS生成语音", "Generate speech via TTS"),
    ("如果voice_service不支持TTS，返回None", "Return None if voice_service lacks TTS"),
    ("使用备用汇报", "Use fallback report"),
    ("将紧急情况记录转换为字典", "Convert emergency record to dict"),
    ("获取紧急情况服务实例", "Get emergency service instance"),
    ("文档分块处理", "Chunk document content"),
    ("为每个分块生成嵌入", "Generate embedding for each chunk"),
    ("使用第一个分块的嵌入作为文档主嵌入（或合并所有嵌入）", "Use first chunk embedding as document embedding (or merge all)"),
    ("存储分块信息到metadata", "Store chunk info in metadata"),
    ("注意：实际生产环境可能需要单独存储", "Note: production may store chunks separately"),
    ("尝试在句号、换行符等位置分割", "Split at sentence boundaries, newlines, etc."),
    ("寻找最佳分割点", "Find best split point"),
    ("移动到下一个分块（考虑重叠）", "Advance to next chunk (with overlap)"),
    ("生成查询向量", "Generate query embedding"),
    ("如果无法生成向量，使用文本搜索", "Fall back to text search if embedding unavailable"),
    ("获取所有文档", "Fetch all documents"),
    ("计算相似度", "Compute similarity"),
    ("标签过滤", "Filter by tags"),
    ("计算余弦相似度", "Compute cosine similarity"),
    ("按相似度排序", "Sort by similarity"),
    ("返回top_k", "Return top_k results"),
    ("更新搜索计数", "Update search count"),
    ("不抛出异常，只记录警告，因为搜索计数更新失败不应该影响搜索结果", "Log warning only; search count failure must not affect results"),
    ("获取对话历史（如果提供conversation_id）", "Load conversation history when conversation_id is provided"),
    ("将最近的问题也加入搜索", "Include recent questions in search"),
    ("构建上下文（增强版 - 考虑对话历史）", "Build context (enhanced, includes conversation history)"),
    ("LLM生成答案（考虑对话历史）", "Generate answer with LLM (includes conversation history)"),
    ("保存对话历史", "Save conversation history"),
    ("提取来源链接", "Extract source links"),
    ("添加问题和答案", "Append question and answer"),
    ("添加文档上下文", "Add document context"),
    ("如果文档有分块，使用最相关的分块", "Use most relevant chunk when document is chunked"),
    ("使用第一个分块（或可以根据问题选择最相关的分块）", "Use first chunk (or pick most relevant per question)"),
    ("添加对话历史上下文（如果有）", "Add conversation history context if present"),
    ("只使用最近3轮对话", "Use only the last 3 conversation turns"),
    ("构建消息历史", "Build message history"),
    ("添加对话历史", "Add conversation history"),
    ("最近4条消息", "Last 4 messages"),
    ("添加当前问题和上下文", "Add current question and context"),
    ("简化异步调用处理", "Simplified async call handling"),
    ("安全地调用AI提供者（简化异步处理）", "Safely call AI provider (simplified async handling)"),
    ("异步调用 - 使用更简单的方法", "Async call - simplified approach"),
    ("尝试获取当前事件循环", "Try to get current event loop"),
    ("如果循环正在运行，使用run_in_executor", "If loop is running, use run_in_executor"),
    ("如果循环未运行，直接使用", "If loop is not running, call directly"),
    ("如果没有事件循环，创建新的", "If no event loop, create one"),
    ("同步调用", "Synchronous call"),
    ("文本搜索（当向量搜索不可用时）", "Text search when vector search unavailable"),
    ("简单的文本匹配", "Simple text matching"),
    ("使用统一的异步调用处理", "Use unified async call handling"),
    ("将文档对象转换为字典", "Convert document to dict"),
    ("获取RAG服务实例", "Get RAG service instance"),
    ("查找现有配置", "Find existing configuration"),
    ("更新现有配置", "Update existing configuration"),
    ("限制在0-100之间", "Clamp to 0-100"),
    ("创建新配置", "Create new configuration"),
    ("如果设置了时间范围，检查当前时间", "If time range is set, check current time"),
    ("处理跨天的情况（如22:00-07:00）", "Handle overnight ranges (e.g. 22:00-07:00)"),
    ("跨天：当前时间在start之后或end之前", "Overnight: current time after start or before end"),
    ("同一天：当前时间在start和end之间", "Same day: current time between start and end"),
    ("将配置转换为字典", "Convert config to dict"),
    ("获取夜间模式服务实例", "Get night mode service instance"),
    ("如果通知类型是提醒类型，尝试使用AI生成温和语气（如果内容为空或使用默认内容）", "For reminder types, use AI gentle tone when content is empty or default"),
    ("实际发送通知（根据delivery_method）", "Deliver notification per delivery_method"),
    ("获取设备令牌", "Get device token"),
    ("获取邮箱地址", "Get email address"),
    ("获取电话号码", "Get phone number"),
    ("in_app通知已经在数据库中记录，不需要额外发送", "in_app notifications are stored in DB; no extra delivery"),
    ("根据接收者类型获取设备", "Get device by recipient type"),
    ("获取用户的主设备", "Get user's primary device"),
    ("家庭成员需要先获取关联的老人ID，然后获取设备", "Family member: resolve linked elder ID then device"),
    ("获取老人的设备（家庭成员可能没有自己的设备）", "Get elder's device (family may have none)"),
    ("获取家庭成员列表", "Get family member list"),
    ("检查通知偏好", "Check notification preferences"),
    ("检查是否应该发送此类型通知", "Check whether this notification type should be sent"),
    ("其他类型默认发送", "Other types sent by default"),
    ("可以根据成员偏好选择", "May follow member preference"),
    ("将通知对象转换为字典", "Convert notification to dict"),
    ("获取通知服务实例", "Get notification service instance"),
    ("构建提示", "Build prompt"),
    ("如果AI生成失败，使用备用提醒", "Use fallback reminder if AI generation fails"),
    ("检查是否有缓存的摘要", "Check for cached summary"),
    ("获取客户信息", "Get customer information"),
    ("获取老人档案（如果是老人）", "Get elder profile when customer is an elder"),
    ("生成摘要", "Generate summary"),
    ("保存摘要", "Save summary"),
    ("24小时过期", "Expires in 24 hours"),
    ("基本信息卡片", "Basic info card"),
    ("解析时间（改进错误处理）", "Parse datetime (improved error handling)"),
    ("支持多种日期格式", "Support multiple date formats"),
    ("如果没有时区信息，假设为UTC", "Assume UTC when timezone is missing"),
    ("验证日期逻辑", "Validate date range logic"),
]

# OpenAPI / longer blocks
MULTILINE: list[tuple[str, str]] = [
    (
        'doc_type 中 medical 为与健康/医疗相关的参考信息分类，内容仅供照护沟通与记录参考，不构成医疗建议。',
        'doc_type medical denotes health/medical reference material for care communication and records; not medical advice.',
    ),
    (
        '添加文档到知识库。doc_type 中 medical 为参考信息分类，内容不构成医疗建议。',
        'Add document to knowledge base. doc_type medical is reference material; not medical advice.',
    ),
    (
        """    summary="用户登录",
    description="使用邮箱、用户名或手机号登录，返回认证令牌。",
    response_description="返回认证令牌和用户信息",
    responses={
        200: {"description": "登录成功"},
        401: {"description": "认证失败，用户名或密码错误"},
        500: {"description": "服务器内部错误"}""",
        """    summary="User login",
    description="Sign in with email, username, or phone; returns an auth token.",
    response_description="Auth token and user profile",
    responses={
        200: {"description": "Login successful"},
        401: {"description": "Authentication failed; invalid credentials"},
        500: {"description": "Internal server error"}""",
    ),
    (
        """    用户登录

    使用标识符（邮箱、用户名或手机号）和密码登录。

    - **identifier**: 用户标识符（邮箱、用户名或手机号）
    - **password**: 密码

    返回 JWT 认证令牌，可用于后续 API 请求的认证。""",
        """    User login

    Sign in with identifier (email, username, or phone) and password.

    - **identifier**: User identifier (email, username, or phone)
    - **password**: Password

    Returns a JWT auth token for subsequent API requests.""",
    ),
    (
        """    summary="获取客户信息",
    description="根据客户ID获取客户详细信息。",
    response_description="返回客户详细信息",
    responses={
        200: {"description": "成功获取客户信息"},
        404: {"description": "客户不存在"},
        401: {"description": "未认证"},
        500: {"description": "服务器内部错误"}""",
        """    summary="Get customer information",
    description="Fetch detailed customer information by customer ID.",
    response_description="Customer details",
    responses={
        200: {"description": "Customer retrieved successfully"},
        404: {"description": "Customer not found"},
        401: {"description": "Not authenticated"},
        500: {"description": "Internal server error"}""",
    ),
    (
        """    获取客户信息

    根据客户ID获取客户的完整信息，包括基本信息和关联的看护者/老人档案。

    - **customer_id**: 客户唯一标识符

    返回客户的详细信息，包括：
    - 基本信息（姓名、联系方式等）
    - 看护者档案（如果是看护者）
    - 老人档案（如果是老人）
    - 关联关系""",
        """    Get customer information

    Fetch full customer record including linked caregiver/elder profiles.

    - **customer_id**: Unique customer identifier

    Returns:
    - Basic info (name, contact, etc.)
    - Caregiver profile (if caregiver)
    - Elder profile (if elder)
    - Relationships""",
    ),
    (
        """    导出用户数据（GDPR 合规）

    导出当前用户的所有数据，包括：
    - 认证信息
    - 用户配置
    - 翻译历史
    - 客户/老人信息
    - 设备信息
    - API 密钥（元数据）
    - 个性化数据
    - 互动历史""",
        """    Export user data (GDPR compliant)

    Export all data for the current user:
    - Authentication info
    - User settings
    - Translation history
    - Customer/elder records
    - Device info
    - API keys (metadata)
    - Personalization data
    - Interaction history""",
    ),
    (
        "下载用户数据（直接下载文件）",
        "Download user data (direct file download)",
    ),
    (
        """    删除账户和所有关联数据（GDPR 合规）

    警告：此操作不可逆！""",
        """    Delete account and all associated data (GDPR compliant)

    Warning: this operation is irreversible!""",
    ),
    (
        '"""接收前端上报的 Web Vitals 数据（已存在，这里扩展）"""',
        '"""Receive Web Vitals reports from the frontend (existing endpoint, extended)."""',
    ),
    (
        '指标类型 (lcp, fid, cls, etc.)',
        'Metric type (lcp, fid, cls, etc.)',
    ),
    (
        '"""获取 Web Vitals 历史数据"""',
        '"""Get Web Vitals historical data"""',
    ),
    (
        '"""获取 Web Vitals 汇总统计"""',
        '"""Get Web Vitals aggregate statistics"""',
    ),
    (
        '"""获取 Web Vitals 告警历史"""',
        '"""Get Web Vitals alert history"""',
    ),
    (
        '"""获取 Web Vitals 告警阈值配置"""',
        '"""Get Web Vitals alert threshold configuration"""',
    ),
    (
        '"""更新 Web Vitals 告警阈值"""',
        '"""Update Web Vitals alert thresholds"""',
    ),
]

# Service docstring param blocks - common patterns
SERVICE_PARAM_PHRASES = [
    ("老人ID", "Elder ID"),
    ("看护者ID", "Caregiver ID"),
    ("机构ID（可选）", "Organization ID (optional)"),
    ("机构ID", "Organization ID"),
    ("开始日期（可选）", "Start date (optional)"),
    ("结束日期（可选）", "End date (optional)"),
    ("限制数量", "Result limit"),
    ("紧急类型（health, emotional, behavioral）", "Emergency type (health, emotional, behavioral)"),
    ("严重程度（low, medium, high）", "Severity (low, medium, high)"),
    ("描述", "Description"),
    ("已采取的行动（可选）", "Actions taken (optional)"),
    ("是否生成AI引导（默认True）", "Generate AI guidance (default True)"),
    ("是否生成简短汇报（默认True）", "Generate brief report (default True)"),
    ("紧急情况记录信息", "Emergency record"),
    ("当前情况描述", "Current situation description"),
    ("免责声明语言（zh, ja, en），默认 ja", "Disclaimer language (zh, ja, en); default ja"),
    ("AI引导信息（语音引导、缓解动作、风险提示）", "AI guidance (voice, relief actions, risk notes)"),
    ("紧急情况记录列表", "List of emergency records"),
    ("引导信息（引导文本、缓解动作、风险提示）", "Guidance (text, relief actions, risk notes)"),
    ("引导文本", "Guidance text"),
    ("语音文件URL（如果成功）", "Voice file URL on success"),
    ("简短汇报文本", "Brief report text"),
    ("备用引导信息", "Fallback guidance"),
    ("文档标题", "Document title"),
    ("文档内容", "Document content"),
    ("文档类型（medical, diet, care_guide）", "Document type (medical, diet, care_guide)"),
    ("分类（可选）", "Category (optional)"),
    ("来源（可选）", "Source (optional)"),
    ("来源URL（可选）", "Source URL (optional)"),
    ("标签列表（可选）", "Tag list (optional)"),
    ("创建者ID（可选）", "Creator ID (optional)"),
    ("是否公开（默认False）", "Public flag (default False)"),
    ("分块大小（字符数，默认500）", "Chunk size in characters (default 500)"),
    ("分块重叠（字符数，默认50）", "Chunk overlap in characters (default 50)"),
    ("创建的文档信息（包含分块信息）", "Created document (includes chunk info)"),
    ("分块大小（字符数）", "Chunk size in characters"),
    ("分块重叠（字符数）", "Chunk overlap in characters"),
    ("分块列表", "List of chunks"),
    ("搜索查询", "Search query"),
    ("文档类型过滤（可选）", "Document type filter (optional)"),
    ("分类过滤（可选）", "Category filter (optional)"),
    ("标签过滤（可选）", "Tag filter (optional)"),
    ("返回数量（默认5）", "Number of results (default 5)"),
    ("相关文档列表（按相似度排序）", "Relevant documents sorted by similarity"),
    ("问题", "Question"),
    ("上下文信息（可选，包含elder_id等）", "Context (optional; elder_id, etc.)"),
    ("检索文档数量（默认3）", "Number of documents to retrieve (default 3)"),
    ("对话ID（用于多轮对话，可选）", "Conversation ID for multi-turn dialogue (optional)"),
    ("答案和来源链接", "Answer and source links"),
    ("用户ID（可选）", "User ID (optional)"),
    ("对话ID", "Conversation ID"),
    ("文本", "Text"),
    ("向量嵌入（列表）", "Embedding vector (list)"),
    ("用户ID", "User ID"),
    ("用户类型（elder, caregiver）", "User type (elder, caregiver)"),
    ("是否启用（可选）", "Enabled flag (optional)"),
    ("亮度（可选）", "Brightness (optional)"),
    ("是否启用声音（可选）", "Sound enabled (optional)"),
    ("是否启用文字提示（可选）", "Text prompts enabled (optional)"),
    ("开始时间（可选，HH:MM格式）", "Start time (optional, HH:MM)"),
    ("结束时间（可选，HH:MM格式）", "End time (optional, HH:MM)"),
    ("声音类型（可选）", "Sound type (optional)"),
    ("音量（可选，0-100）", "Volume (optional, 0-100)"),
    ("字体大小（可选）", "Font size (optional)"),
    ("配色方案（可选）", "Color scheme (optional)"),
    ("更新后的配置", "Updated configuration"),
    ("夜间模式配置（如果存在）", "Night mode config if present"),
    ("是否激活", "Whether night mode is active"),
    ("接收者类型（caregiver, elder, family_member）", "Recipient type (caregiver, elder, family_member)"),
    ("接收者ID", "Recipient ID"),
    ("通知类型（task_reminder, schedule_reminder, emergency等）", "Notification type (task_reminder, schedule_reminder, emergency, etc.)"),
    ("通知标题", "Notification title"),
    ("通知内容", "Notification content"),
    ("关联任务ID（可选）", "Related task ID (optional)"),
    ("关联日程ID（可选）", "Related schedule ID (optional)"),
    ("关联活动ID（可选）", "Related activity ID (optional)"),
    ("发送方式（push, email, sms, in_app）", "Delivery method (push, email, sms, in_app)"),
    ("创建的通知信息", "Created notification"),
    ("通知对象", "Notification object"),
    ("发送方式", "Delivery method"),
    ("发送的通知列表", "List of sent notifications"),
    ("接收者类型（可选）", "Recipient type (optional)"),
    ("是否已读（可选）", "Read flag (optional)"),
    ("返回数量限制", "Result limit"),
    ("通知列表", "Notification list"),
    ("通知ID", "Notification ID"),
    ("是否成功标记", "Whether mark succeeded"),
    ("标记的数量", "Number marked"),
    ("提醒类型（task, schedule, medication, exercise等）", "Reminder type (task, schedule, medication, exercise, etc.)"),
    ("任务标题（可选）", "Task title (optional)"),
    ("日程标题（可选）", "Schedule title (optional)"),
    ("截止时间（可选）", "Due time (optional)"),
    ("上下文信息（可选）", "Context (optional)"),
    ("温和语气的提醒文本", "Gentle-tone reminder text"),
    ("提醒类型", "Reminder type"),
    ("标题", "Title"),
    ("备用提醒文本", "Fallback reminder text"),
    ("客户ID", "Customer ID"),
    ("摘要类型（full, health, preferences, activities）", "Summary type (full, health, preferences, activities)"),
    ("是否强制重新生成", "Force regeneration"),
    ("摘要信息", "Summary data"),
    ("信息卡片数据", "Information card data"),
    ("记录紧急情况", "Record an emergency"),
    ("获取AI紧急引导", "Get AI emergency guidance"),
    ("获取紧急情况历史记录", "Get emergency history"),
    ("生成AI引导（内部方法）", "Generate AI guidance (internal)"),
    ("生成语音引导（TTS）", "Generate voice guidance (TTS)"),
    ("生成紧急情况简短汇报", "Generate brief emergency report"),
    ("获取备用引导（当AI不可用时）", "Get fallback guidance when AI unavailable"),
    ("添加文档到知识库（支持文档分块）", "Add document to knowledge base (with chunking)"),
    ("搜索相关文档", "Search relevant documents"),
    ("RAG问答（支持多轮对话）", "RAG Q&A (multi-turn dialogue)"),
    ("创建新对话", "Create new conversation"),
    ("获取对话历史", "Get conversation history"),
    ("保存对话消息", "Save conversation message"),
    ("构建增强的上下文（考虑对话历史）", "Build enhanced context with conversation history"),
    ("使用LLM生成答案（考虑对话历史）", "Generate answer with LLM using conversation history"),
    ("生成文本向量嵌入", "Generate text embedding"),
    ("获取夜间模式配置", "Get night mode configuration"),
    ("更新夜间模式配置", "Update night mode configuration"),
    ("检查夜间模式是否激活", "Check whether night mode is active"),
    ("发送通知", "Send notification"),
    ("实际发送通知", "Deliver notification"),
    ("发送通知给家庭成员", "Send notification to family members"),
    ("获取通知列表", "Get notification list"),
    ("标记通知为已读", "Mark notification as read"),
    ("标记所有通知为已读", "Mark all notifications as read"),
    ("生成温和语气的提醒（AI生成）", "Generate gentle-tone reminder (AI)"),
    ("获取备用提醒（当AI不可用时）", "Get fallback reminder when AI unavailable"),
    ("生成客户信息摘要", "Generate customer information summary"),
]

PHRASES.extend(SERVICE_PARAM_PHRASES)

# Pass 2: partial fixes, models, remaining services
PASS2: list[tuple[str, str]] = [
    ("自定义异常 - 应用特定的异常类", ""),
    ("安全工具 - 安全相关的辅助函数", ""),
    ("工具模块", ""),
    ("获取所有照护术语", "Get all care terms"),
    ("搜索术语", "Search terms"),
    ("翻译单个术语", "Translate a single term"),
    ("获取照护场景模板", "Get care scenario templates"),
    ("Parse dates（改进错误处理）", "Parse dates (improved error handling)"),
    ("包含：completed_tasks, emotion_score, recent_activities等", "Includes completed_tasks, emotion_score, recent_activities, etc."),
    ("最近的情绪日志", "Recent emotion logs"),
    ("其他偏好", "Other preferences"),
    ("活动记录请求模型", "Activity record request model"),
    ("活动分类", "Activity category"),
    ("难度：easy, medium, hard", "Difficulty: easy, medium, hard"),
    ("获取活动模板列表", "Get activity template list"),
    ("获取单个活动模板详情", "Get single activity template details"),
    ("根据老人信息推荐活动", "Recommend activities based on elder profile"),
    ("创建活动记录", "Create activity record"),
    ("获取活动记录列表", "Get activity record list"),
    ("获取单个活动记录详情", "Get single activity record details"),
    ("获取活动分类列表", "Get activity category list"),
    ("Task Management Service - 任务管理服务", "Task Management Service"),
    ("Schedule Management Service - 日程管理服务", "Schedule Management Service"),
    ("SMS Notification Service - 短信Notification service", "SMS Notification Service"),
    ("语音服务 - Speech-to-text和Text-to-speech", "Voice Service - Speech-to-text and Text-to-speech"),
    ("任务管理服务", "Task management service"),
    ("日程管理服务", "Schedule management service"),
    ("短信Notification service", "SMS notification service"),
    ("短信Notification service（Twilio）", "SMS notification service (Twilio)"),
    ("任务Title", "Task title"),
    ("任务Description", "Task description"),
    ("日程Title", "Schedule title"),
    ("Caregiver ID（可选）", "Caregiver ID (optional)"),
    ("Elder ID（可选）", "Elder ID (optional)"),
    ("Family member ID列表", "Family member ID list"),
    ("关系ID", "Relationship ID"),
    ("创建的任务信息", "Created task info"),
    ("任务状态（可选）", "Task status (optional)"),
    ("任务类型（可选）", "Task type (optional)"),
    ("任务列表", "Task list"),
    ("任务ID", "Task ID"),
    ("进度（0-100，可选）", "Progress (0-100, optional)"),
    ("备注（可选）", "Notes (optional)"),
    ("完成者ID", "Completed-by user ID"),
    ("完成备注（可选）", "Completion notes (optional)"),
    ("是否生成AI总结（可选）", "Generate AI summary (optional)"),
    ("完成后的任务信息", "Completed task info"),
    ("进度数据", "Progress data"),
    ("日期（默认为今天）", "Date (defaults to today)"),
    ("每日总结（温和、鼓励的语气）", "Daily summary (gentle, encouraging tone)"),
    ("生成温和的总结Text", "Generate gentle summary text"),
    ("将任务对象转换为字典", "Convert task to dict"),
    ("计算剩余时间（秒）", "Compute remaining time (seconds)"),
    ("检查任务是否逾期", "Check whether task is overdue"),
    ("生成任务完成总结（AI生成）", "Generate task completion summary (AI)"),
    ("完成总结Text", "Completion summary text"),
    ("集成AI生成总结", "Integrate AI summary generation"),
    ("暂时返回简单总结", "Return simple summary for now"),
    ("生成每日总结Text（温和、鼓励的语气）", "Generate daily summary text (gentle, encouraging tone)"),
    ("已Complete task列表", "Completed task list"),
    ("待办任务列表", "Pending task list"),
    ("进行中任务列表", "In-progress task list"),
    ("总结Text", "Summary text"),
    ("基础总结", "Base summary"),
    ("最多显示3个", "Show at most 3"),
    ("使用AI生成更个性化的总结", "Use AI for more personalized summary"),
    ("获取任务服务实例", "Get task service instance"),
    ("限制在0-100", "Clamp to 0-100"),
    ("生成AI总结（如果启用）", "Generate AI summary if enabled"),
    ("支持Twilio SMS", "Supports Twilio SMS"),
    ("发送短信", "Send SMS"),
    ("收件人电话号码（E.164格式，如+819012345678）", "Recipient phone (E.164, e.g. +819012345678)"),
    ("短信内容", "SMS message body"),
    ("是否成功发送", "Whether send succeeded"),
    ("批量发送短信", "Send SMS in batch"),
    ("收件人电话号码列表", "Recipient phone list"),
    ("发送结果字典 {phone: success}", "Send results dict {phone: success}"),
    ("全局实例", "Global instance"),
    ("获取短信服务实例（单例模式）", "Get SMS service instance (singleton)"),
    ("Task Management Models - 任务管理数据模型", "Task Management Models"),
    ("Emergency and Night Mode Models - 紧急情况和夜间模式数据模型", "Emergency and Night Mode Models"),
    ("Summary and Change Tracking Models - 信息摘要和变化追踪数据模型", "Summary and Change Tracking Models"),
    ("客户信息数据模型 - 用于个性化优化", "Customer data models for personalization"),
    ("数据库模型 - 仅数据模型，不包含配置", "Database models only (no configuration)"),
    ("支持模型 - 工单系统", "Support models - ticket system"),
    ("帮助中心模型 - 帮助文章和常见Question", "Help center models - articles and FAQs"),
    ("反馈模型 - 用户反馈和建议", "Feedback models - user feedback and suggestions"),
    ("任务表", "Task table"),
    ("日程表", "Schedule table"),
    ("情绪日志表", "Emotion log table"),
    ("支持工单表", "Support ticket table"),
    ("工单消息表", "Ticket message table"),
    ("工单活动日志表", "Ticket activity log table"),
    ("信息变化日志表", "Information change log table"),
    ("客户信息摘要表（缓存）", "Customer summary cache table"),
    ("RAG对话历史表（用于多轮对话）", "RAG conversation history table (multi-turn)"),
    ("帮助文章表", "Help article table"),
    ("常见Question表", "FAQ table"),
    ("帮助反馈表", "Help feedback table"),
    ("用户反馈表", "User feedback table"),
    ("反馈评论表（用于反馈讨论）", "Feedback comment table (discussion thread)"),
    ("满意度调查表", "Satisfaction survey table"),
    ("紧急情况记录表", "Emergency record table"),
    ("夜间模式配置表", "Night mode configuration table"),
    ("机构（介护机构）数据表", "Organization (care facility) table"),
    ("用户个人配置数据表", "User profile settings table"),
    ("翻译历史记录表", "Translation history table"),
    ("使用统计表（按机构/用户/日期）", "Usage statistics table (org/user/date)"),
    ("活动模板库", "Activity template library"),
    ("活动记录表", "Activity record table"),
    ("活动推荐记录表", "Activity recommendation record table"),
    ("客户主表（看护者或老人）", "Customer master table (caregiver or elder)"),
    ("看护者详细信息表", "Caregiver profile table"),
    ("老人详细信息表", "Elder profile table"),
    ("基本信息", "Basic information"),
    ("关联信息", "Relationship / linkage fields"),
    ("参与者（家庭成员等）", "Participants (family members, etc.)"),
    ("任务状态", "Task status"),
    ("时间信息", "Timestamps"),
    ("进度信息", "Progress fields"),
    ("提醒设置", "Reminder settings"),
    ("其他信息", "Other fields"),
    ("额外元数据", "Extra metadata"),
    ("完成信息", "Completion fields"),
    ("AI生成的完成总结", "AI-generated completion summary"),
    ("自定义重复模式", "Custom recurrence pattern"),
    ("参与者", "Participants"),
    ("List[str] - 参与者ID列表", "List[str] - participant user IDs"),
    ("是否共享给家庭成员", "Shared with family members"),
    ("List[str] - 共享给的Family member ID", "List[str] - family member IDs shared with"),
    ("关联任务（如果日程关联到任务）", "Linked task when schedule maps to a task"),
    ("用户信息", "User fields"),
    ("情绪信息", "Emotion fields"),
    ("1-5分", "Score 1-5"),
    ("详细记录", "Detailed record"),
    ("可选文字说明", "Optional text notes"),
    ("可选语音记录URL", "Optional voice note URL"),
    ("上下文信息（活动、天气、健康状况等）", "Context (activity, weather, health, etc.)"),
    ("元数据", "Metadata"),
    ("工单信息", "Ticket fields"),
    ("主题", "Subject"),
    ("子分类", "Subcategory"),
    ("状态管理", "Status management"),
    ("分配信息", "Assignment fields"),
    ("分配给（支持人员ID）", "Assigned to (support staff ID)"),
    ("解决信息", "Resolution fields"),
    ("解决方案", "Resolution text"),
    ("附件列表", "Attachment list"),
    ("标签", "Tags"),
    ("其他元数据（metadata是SQLAlchemy保留字）", "Other metadata (metadata is SQLAlchemy reserved)"),
    ("首次响应时间", "First response time"),
    ("最后响应时间", "Last response time"),
    ("发送人ID", "Sender user ID"),
    ("是否为内部消息（用户不可见）", "Internal message (hidden from user)"),
    ("是否为管理员消息", "Admin message flag"),
    ("消息内容", "Message body"),
    ("操作人ID", "Actor user ID"),
    ("活动信息", "Activity fields"),
    ("活动数据", "Activity payload"),
    ("变化的Field name", "Changed field name"),
    ("旧值", "Old value"),
    ("新值", "New value"),
    ("变化详情", "Change details"),
    ("变化摘要", "Change summary"),
    ("修改者ID", "Changed-by user ID"),
    ("摘要Text", "Summary text"),
    ("摘要结构化数据", "Structured summary data"),
    ("关键信息（需求、情绪、健康状态等）", "Key info (needs, mood, health, etc.)"),
    ("最近更新的字段列表", "Recently updated field names"),
    ("摘要过期时间", "Summary expiry time"),
    ("对话消息列表", "Conversation messages"),
    ("使用的文档ID列表", "Referenced document IDs"),
    ("状态", "Status"),
    ("文章信息", "Article fields"),
    ("日文Title", "Japanese title"),
    ("中文Title", "Chinese title"),
    ("内容", "Content"),
    ("日文内容", "Japanese content"),
    ("中文内容", "Chinese content"),
    ("分类和标签", "Category and tags"),
    ("分类", "Category"),
    ("标签列表", "Tag list"),
    ("查看次数", "View count"),
    ("有帮助次数", "Helpful vote count"),
    ("无帮助次数", "Not helpful vote count"),
    ("是否推荐", "Featured flag"),
    ("显示顺序", "Display order"),
    ("Question信息", "Question fields"),
    ("日文Question", "Japanese question"),
    ("中文Question", "Chinese question"),
    ("答案", "Answer"),
    ("日文答案", "Japanese answer"),
    ("中文答案", "Chinese answer"),
    ("关联文章ID", "Linked article ID"),
    ("关联FAQ ID", "Linked FAQ ID"),
    ("评论", "Comment"),
    ("User ID（可选，支持匿名反馈）", "User ID (optional; anonymous feedback supported)"),
    ("反馈类型", "Feedback type"),
    ("联系信息（可选）", "Contact info (optional)"),
    ("处理信息", "Handling fields"),
    ("分配给（管理员ID）", "Assigned to (admin ID)"),
    ("解决方案/回复", "Resolution / reply"),
    ("解决时间", "Resolved at"),
    ("解决人", "Resolved by"),
    ("用户代理", "User agent"),
    ("IP地址", "IP address"),
    ("反馈时的页面URL", "Page URL when feedback was submitted"),
    ("评论人ID", "Commenter user ID"),
    ("是否为管理员评论", "Admin comment flag"),
    ("评论内容", "Comment body"),
    ("调查内容", "Survey fields"),
    ("各项评分", "Per-item ratings"),
    ("已采取的行动", "Actions taken"),
    ("AI生成的Guidance text", "AI-generated guidance text"),
    ("语音引导URL（TTS生成）", "Voice guidance URL (TTS)"),
    ("缓解动作建议", "Suggested relief actions"),
    ("风险提示", "Risk notes"),
    ("简短汇报（AI生成）", "Brief report (AI-generated)"),
    ("通知信息", "Notification fields"),
    ("已通知的联系人ID", "Notified contact IDs"),
    ("夜间模式设置", "Night mode settings"),
    ("HH:MM格式，如\"22:00\"", "HH:MM format, e.g. \"22:00\""),
    ("HH:MM格式，如\"07:00\"", "HH:MM format, e.g. \"07:00\""),
    ("声音设置", "Sound settings"),
    ("界面设置", "UI settings"),
    ("机构唯一标识", "Organization unique ID"),
    ("机构名称", "Organization name"),
    ("机构名称（日语）", "Organization name (Japanese)"),
    ("机构信息", "Organization fields"),
    ("机构类型：特别养护老人院、介护老人保健设施等", "Org type: nursing home, health facility, etc."),
    ("机构配置", "Organization configuration"),
    ("机构级自定义术语", "Org-level custom terms"),
    ("机构常用照护场景", "Org care scenario presets"),
    ("订阅和限制", "Subscription and limits"),
    ("最大用户数", "Max users"),
    ("每月翻译次数限制", "Monthly translation quota"),
    ("统计", "Statistics"),
    ("总翻译次数", "Total translations"),
    ("活跃用户数", "Active user count"),
    ("所属Organization ID", "Organization ID"),
    ("个人信息", "Personal info"),
    ("日语名称", "Japanese name"),
    ("照护者角色：介护士、家属等", "Caregiver role: nurse, family, etc."),
    ("照护经验年数", "Years of care experience"),
    ("语言偏好", "Language preferences"),
    ("翻译偏好", "Translation preferences"),
    ("是否使用敬语", "Use honorifics"),
    ("照护场景偏好", "Care scenario preferences"),
    ("常用照护场景列表", "Frequent care scenarios"),
    ("自定义术语词典", "Custom term dictionary"),
    ("工作习惯", "Work habits"),
    ("工作时间：day, night, both", "Work shift: day, night, both"),
    ("常用任务列表", "Common task list"),
    ("个性化设置", "Personalization settings"),
    ("其他个性化设置", "Other preferences"),
    ("权限和状态", "Permissions and status"),
    ("原文长度", "Source text length"),
    ("翻译耗时（毫秒）", "Translation duration (ms)"),
    ("使用的AI提供商", "AI provider used"),
    ("语言对统计", "Language-pair statistics"),
    ("分类和标签", "Category and tags"),
    ("所需材料列表", "Required materials list"),
    ("参与人数", "Participant count"),
    ("适用人群", "Suitable audience"),
    ("健康注意事项", "Health considerations"),
    ("活动内容", "Activity content"),
    ("活动步骤", "Activity steps"),
    ("活动提示", "Activity tips"),
    ("活动变体", "Activity variants"),
    ("创建者（机构或系统）", "Creator (org or system)"),
    ("使用次数", "Usage count"),
    ("平均评分", "Average rating"),
    ("分享和社区", "Sharing and community"),
    ("是否分享到社区", "Shared to community"),
    ("分享次数", "Share count"),
    ("多媒体支持", "Multimedia"),
    ("图片URL列表", "Image URL list"),
    ("视频URL列表", "Video URL list"),
    ("音频URL列表", "Audio URL list"),
    ("基于哪个模板", "Source template ID"),
    ("活动详情", "Activity details"),
    ("定制化的活动步骤", "Customized activity steps"),
    ("实际使用的材料", "Materials actually used"),
    ("活动过程", "Activity session"),
    ("实际持续时间", "Actual duration (minutes)"),
    ("活动笔记", "Activity notes"),
    ("效果评估", "Effectiveness evaluation"),
    ("活动前情绪", "Mood before activity"),
    ("活动后情绪", "Mood after activity"),
    ("看护者反馈", "Caregiver feedback"),
    ("老人反馈（如果有）", "Elder feedback (if any)"),
    ("成果记录", "Outcomes record"),
    ("活动照片URL列表", "Activity photo URLs"),
    ("活动视频URL列表", "Activity video URLs"),
    ("活动成果Description", "Activity outcome description"),
    ("协同设计", "Co-design"),
    ("协同设计者列表", "Co-designer list"),
    ("设计笔记", "Design notes"),
    ("家属参与", "Family participation"),
    ("参与的家属列表", "Participating family members"),
    ("家属反馈", "Family feedback"),
    ("语音相关", "Voice-related fields"),
    ("语音笔记URL列表", "Voice note URLs"),
    ("推荐信息", "Recommendation fields"),
    ("推荐的活动列表", "Recommended activities"),
    ("推荐理由", "Recommendation rationale"),
    ("老人的信息快照", "Elder profile snapshot"),
    ("推荐状态", "Recommendation status"),
    ("选择的活动ID", "Selected activity ID"),
    ("客户唯一标识", "Customer unique ID"),
    ("中文名称", "Chinese name"),
    ("联系信息", "Contact info"),
    ("出生日期", "Birth date"),
    ("年龄（计算得出）", "Age (computed)"),
    ("地址信息", "Address fields"),
    ("都道府县（日本）", "Prefecture (Japan)"),
    ("语言信息", "Language fields"),
    ("母语", "Native language"),
    ("会说的语言列表", "Spoken languages"),
    ("偏好语言", "Preferred language"),
    ("所属机构", "Organization ID"),
    ("关联的User ID（如果是看护者）", "Linked user ID (if caregiver)"),
    ("职业信息", "Professional info"),
    ("介护士、看护助手、家属等", "Role: nurse, aide, family, etc."),
    ("资格证书列表", "Certifications"),
    ("工作信息", "Work info"),
    ("工作时间表", "Work schedule"),
    ("专长领域：", "Specialties: "),
    ("照护偏好", "Care preferences"),
    ("健康状况", "Health status"),
    ("疾病列表：", "Conditions: "),
    ("日常生活能力", "Activities of daily living"),
    ("日常生活活动能力评分", "ADL scores"),
    ("工具性日常生活活动能力评分", "IADL scores"),
    ("兴趣和爱好", "Interests and hobbies"),
    ("健康信息卡片", "Health info card"),
    ("情绪模式卡片", "Emotion pattern card"),
    ("最近变化卡片", "Recent changes card"),
    ("起始时间（可选）", "Since timestamp (optional)"),
    ("变化Category (optional)", "Change category (optional)"),
    ("变化列表", "Change list"),
    ("生成变化摘要", "Generate change summary"),
    ("自动分类", "Auto-categorize change"),
    ("获取缓存的摘要", "Get cached summary"),
    ("构建摘要数据", "Build summary payload"),
    ("提取关键信息", "Extract key information"),
    ("需求（从健康条件和能力推断）", "Inferred needs from health and abilities"),
    ("情绪模式", "Emotion patterns"),
    ("获取最近变化的字段列表", "Get recently changed field names"),
    ("将摘要对象转换为字典", "Convert summary to dict"),
    ("将变化对象转换为字典", "Convert change record to dict"),
    ("获取摘要服务实例", "Get summary service instance"),
    ("确保参与者包含看护者和老人", "Ensure participants include caregiver and elder"),
    ("按日期分组", "Group by date"),
    ("获取日程服务实例", "Get schedule service instance"),
    ("Speech-to-text功能待实现", "Speech-to-text not yet implemented"),
    ("    使用标识符（邮箱、用户名或手机号）和密码登录。", "    Sign in with identifier (email, username, or phone) and password."),
    ("    - **identifier**: 用户标识符（邮箱、用户名或手机号）", "    - **identifier**: User identifier (email, username, or phone)"),
    ("    - **password**: 密码", "    - **password**: Password"),
    ("    返回 JWT 认证令牌，可用于后续 API 请求的认证。", "    Returns a JWT auth token for subsequent API requests."),
    ("    根据Customer ID获取客户的完整信息，包括基本信息和关联的看护者/老人档案。", "    Fetch full customer record by ID, including linked caregiver/elder profiles."),
    ("    - **customer_id**: 客户唯一标识符", "    - **customer_id**: Unique customer identifier"),
    ("    返回客户的详细信息，包括：", "    Returns customer details including:"),
    ("    - 基本信息（姓名、联系方式等）", "    - Basic info (name, contact, etc.)"),
    ("    - 看护者档案（如果是看护者）", "    - Caregiver profile (if caregiver)"),
    ("    - 老人档案（如果是老人）", "    - Elder profile (if elder)"),
    ("    - 关联关系", "    - Relationships"),
    ("    导出用户数据（GDPR 合规）", "    Export user data (GDPR compliant)"),
    ("    导出当前用户的所有数据，包括：", "    Export all data for the current user, including:"),
    ("    - 认证信息", "    - Authentication info"),
    ("    - 用户配置", "    - User settings"),
    ("    - 翻译历史", "    - Translation history"),
    ("    - 客户/老人信息", "    - Customer/elder records"),
    ("    - 设备信息", "    - Device info"),
    ("    - API 密钥（元数据）", "    - API keys (metadata)"),
    ("    - 个性化数据", "    - Personalization data"),
    ("    - 互动历史", "    - Interaction history"),
    ("    删除账户和所有关联数据（GDPR 合规）", "    Delete account and all associated data (GDPR compliant)"),
    ("    警告：此操作不可逆！", "    Warning: this operation is irreversible!"),
]

PASS3: list[tuple[str, str]] = [
    ("Register a new user请求", "Register a new user request"),
    ("User login请求", "User login request"),
    ("设备注册请求", "Device registration request"),
    ("推送Notification service（FCM）", "Push notification service (FCM)"),
    ("发送推送通知", "Send push notification"),
    ("设备令牌（FCM token）", "Device token (FCM token)"),
    ("额外数据（可选）", "Extra data (optional)"),
    ("批量发送推送通知", "Send push notifications in batch"),
    ("设备令牌列表", "Device token list"),
    ("获取推送服务实例（单例模式）", "Get push service instance (singleton)"),
    ("家庭成员管理服务", "Family member management service"),
    ("姓名", "Name"),
    ("关系（son, daughter, spouse等）", "Relationship (son, daughter, spouse, etc.)"),
    ("电话（可选）", "Phone (optional)"),
    ("邮箱（可选）", "Email (optional)"),
    ("日语姓名（可选）", "Japanese name (optional)"),
    ("中文姓名（可选）", "Chinese name (optional)"),
    ("通知偏好（可选）", "Notification preferences (optional)"),
    ("可查看任务（默认True）", "Can view tasks (default True)"),
    ("可查看日程（默认True）", "Can view schedules (default True)"),
    ("可查看情绪（默认False）", "Can view emotions (default False)"),
    ("可查看活动（默认True）", "Can view activities (default True)"),
    ("创建的家庭成员信息", "Created family member info"),
    ("默认通知偏好", "Default notification preferences"),
    ("是否活跃（可选）", "Active flag (optional)"),
    ("家庭成员列表", "Family member list"),
    ("更新后的家庭成员信息", "Updated family member info"),
    ("是否成功删除", "Whether delete succeeded"),
    ("将家庭成员对象转换为字典", "Convert family member to dict"),
    ("获取家庭成员服务实例", "Get family service instance"),
    ("家庭成员参与服务", "Family participation service"),
    ("验证家庭成员", "Validate family member"),
    ("检查权限", "Check permissions"),
    ("验证elder_id匹配", "Validate elder_id match"),
    ("验证org_id匹配（如果提供）", "Validate org_id match when provided"),
    ("日程ID", "Schedule ID"),
    ("更新后的日程信息", "Updated schedule info"),
    ("Organization ID（可选，用于权限验证）", "Organization ID (optional, for authorization)"),
    ("验证家庭成员存在", "Verify family member exists"),
    ("验证org_id（如果提供）", "Validate org_id when provided"),
    ("使用JSON字段查询（SQLAlchemy的contains对JSON字段是安全的，使用参数化查询）", "JSON contains query via SQLAlchemy (parameterized, safe for JSON columns)"),
    ("注意：family_member_ids是JSON数组，使用contains检查是否包含该ID", "Note: family_member_ids is a JSON array; contains checks membership"),
    ("添加elder_id过滤以提高性能和安全性", "Filter by elder_id for performance and security"),
    ("获取家庭成员参与服务实例", "Get family participation service instance"),
    ("家庭成员反馈（使用JSON存储，或可以创建独立表）", "Family feedback (JSON storage; may move to dedicated table)"),
    ("家庭成员反馈服务", "Family feedback service"),
    ("评分（1-5，可选）", "Rating (1-5, optional)"),
    ("反馈信息", "Feedback info"),
    ("Family member ID（可选）", "Family member ID (optional)"),
    ("Feedback type（可选）", "Feedback type (optional)"),
    ("反馈列表", "Feedback list"),
    ("天数", "Number of days"),
    ("反馈摘要", "Feedback summary"),
    ("过滤时间", "Filter by time range"),
    ("最近10条", "Last 10 entries"),
    ("获取家庭成员反馈服务实例", "Get family feedback service instance"),
    ("情绪日志服务", "Emotion logging service"),
    ("User ID（老人或看护者）", "User ID (elder or caregiver)"),
    ("情绪分数（Score 1-5）", "Emotion score (1-5)"),
    ("情绪类型（happy, sad, anxious, calm等，可选）", "Emotion type (happy, sad, anxious, calm, etc.; optional)"),
    ("文字说明（可选）", "Text notes (optional)"),
    ("语音记录URL（可选）", "Voice note URL (optional)"),
    ("记录的情绪日志信息", "Recorded emotion log"),
    ("验证情绪分数", "Validate emotion score"),
    ("验证用户类型", "Validate user type"),
    ("用户类型（可选）", "User type (optional)"),
    ("情绪历史列表", "Emotion history list"),
    ("Number of days to analyze（默认30天）", "Number of days to analyze (default 30)"),
    ("情绪分析结果", "Emotion analysis result"),
    ("计算平均分数", "Compute average score"),
    ("情绪分布", "Emotion distribution"),
    ("趋势分析", "Trend analysis"),
    ("最近7天", "Last 7 days"),
    ("前7天", "Prior 7 days"),
    ("模式识别", "Pattern detection"),
    ("Generate positive feedback（AI生成 - 集成GPT-4）", "Generate positive feedback (AI via GPT-4)"),
    ("上下文信息（完成的任务、情绪分数、最近活动等）", "Context (completed tasks, emotion score, recent activities, etc.)"),
    ("正向反馈Text", "Positive feedback text"),
    ("异步调用", "Async invocation"),
    ("如果AI生成失败，使用备用反馈", "Use fallback feedback if AI generation fails"),
    ("使用备用反馈", "Use fallback feedback"),
    ("生成备用反馈（当AI不可用时）", "Generate fallback feedback when AI unavailable"),
    ("Detect stress signals（增强版 - 集成AI分析）", "Detect stress signals (enhanced with AI analysis)"),
    ("工作量数据（可选）", "Workload data (optional)"),
    ("压力检测结果", "Stress detection result"),
    ("分析情绪日志", "Analyze emotion logs"),
    ("计算压力评分（1-10，10为最高压力）", "Compute stress score (1-10; 10 is highest)"),
    ("使用AI生成个性化建议（如果压力较高）", "Use AI for personalized suggestions when stress is high"),
    ("合并用户和机构的配置", "Merge user and organization settings"),
    ("合并Org-level custom terms", "Merge org-level custom terms"),
    ("合并机构级照护场景", "Merge org-level care scenarios"),
    ("去重", "Deduplicate"),
    ("翻译总数", "Total translation count"),
    ("每日Statistics", "Daily statistics"),
    ("检查本月翻译次数", "Check monthly translation count"),
    ("更新机构总翻译数", "Update org total translation count"),
    ("更新每日Statistics", "Update daily statistics"),
    ("支付记录表", "Payment record table"),
    ("支付信息", "Payment fields"),
    ("金额", "Amount"),
    ("货币", "Currency"),
    ("支付Status", "Payment status"),
    ("订阅信息", "Subscription fields"),
    ("关联订阅", "Linked subscription"),
    ("订阅计划ID", "Subscription plan ID"),
    ("收据URL", "Receipt URL"),
    ("订阅表", "Subscription table"),
    ("订阅创建人", "Subscription creator"),
    ("订阅Status", "Subscription status"),
    ("计费信息", "Billing fields"),
    ("月费", "Monthly fee"),
    ("自动续费", "Auto-renewal"),
    ("发票表", "Invoice table"),
    ("发票信息", "Invoice fields"),
    ("发票编号", "Invoice number"),
    ("发票Status", "Invoice status"),
    ("发票Content", "Invoice content"),
    ("发票项目列表", "Invoice line items"),
    ("账单地址", "Billing address"),
    ("知识库文档表", "Knowledge base document table"),
    ("来源（厚生労働省等）", "Source (e.g. MHLW)"),
    ("Tags和Category", "Tags and category"),
    ("向量嵌入（用于RAG）", "Vector embedding (for RAG)"),
    ("List[float] - 存储向量嵌入", "List[float] - stored embedding vector"),
    ("是否公开", "Public flag"),
    ("搜索次数", "Search count"),
    ("家庭成员表", "Family member table"),
    ("通知偏好", "Notification preferences"),
    ("权限设置", "Permission settings"),
    ("默认不允许查看情绪", "Emotions hidden by default"),
    ("是否已验证", "Verified flag"),
    ("通知表", "Notification table"),
    ("接收者信息", "Recipient fields"),
    ("发送信息", "Delivery fields"),
    ("共享设置", "Sharing settings"),
    ("上下文信息", "Context fields"),
    ("变化信息", "Change fields"),
    ("关键信息", "Key info fields"),
    ("对话信息", "Conversation fields"),
    ("紧急情况信息", "Emergency fields"),
    ("AI引导信息", "AI guidance fields"),
    ("简短汇报", "Brief report"),
    ("时间设置", "Time settings"),
    ("Statistics信息", "Statistics fields"),
    ("YYYY-MM-DD格式", "YYYY-MM-DD format"),
    ("适用性", "Applicability"),
    ("用户认证表", "User authentication table"),
    ("认证信息", "Authentication fields"),
    ("密码（加密存储）", "Password (hashed)"),
    ("使用 bcrypt 加密", "bcrypt hash"),
    ("认证方式", "Auth method"),
    ("OAuth 信息", "OAuth fields"),
    ("已Register a device列表", "Registered device list"),
    ("安全设置", "Security settings"),
    ("设备信息表", "Device info table"),
    ("用户自定义名称", "User-defined device name"),
    ("设备标识", "Device identifiers"),
    ("设备唯一标识", "Unique device ID"),
    ("推送通知token", "Push notification token"),
    ("同步信息", "Sync fields"),
    ("是否为主设备", "Primary device flag"),
    ("数据同步日志表", "Data sync log table"),
    ("同步数据", "Synced payload"),
    ("同步结果", "Sync result"),
    ("数据版本控制表（用于冲突检测）", "Data version table (conflict detection)"),
    ("数据标识", "Data identifiers"),
    ("具体数据记录的ID", "Record ID"),
    ("版本信息", "Version fields"),
    ("版本号", "Version number"),
    ("最后修改的设备ID", "Last modified by device ID"),
    ("冲突标记", "Conflict flags"),
    ("API 密钥表", "API key table"),
    ("API密钥（哈希存储）", "API key (hashed)"),
    ("密钥哈希值", "Key hash"),
    ("关联用户（可选）", "Linked user (optional)"),
    ("关联机构（可选）", "Linked organization (optional)"),
    ("密钥信息", "Key metadata"),
    ("密钥名称/Description", "Key name / description"),
    ("权限列表", "Permission list"),
    ("使用限制", "Usage limits"),
    ("速率限制", "Rate limit"),
    ("每日最大请求数", "Max requests per day"),
    ("总请求数", "Total request count"),
    ("最后使用时间", "Last used at"),
    ("最后使用IP", "Last used IP"),
    ("过期时间（可选）", "Expiry time (optional)"),
    ("用户事件表", "User event table"),
    ("会话ID", "Session ID"),
    ("事件信息", "Event fields"),
    ("事件Category", "Event category"),
    ("事件数据", "Event payload"),
    ("事件属性", "Event properties"),
    ("用户会话表", "User session table"),
    ("会话信息", "Session fields"),
    ("会话数据", "Session payload"),
    ("设备信息", "Device info"),
    ("转化漏斗步骤表", "Conversion funnel step table"),
    ("漏斗信息", "Funnel fields"),
    ("漏斗名称", "Funnel name"),
    ("步骤名称", "Step name"),
    ("步骤顺序", "Step order"),
    ("到达此步骤的用户数", "Users reaching this step"),
    ("转化率", "Conversion rate"),
    ("照护关系表（看护者和老人的关联）", "Care relationship table (caregiver-elder link)"),
    ("关系信息", "Relationship fields"),
    ("关系开始日期", "Relationship start date"),
    ("照护频率", "Care frequency"),
    ("每次照护时长", "Hours per care session"),
    ("关系质量指标", "Relationship quality metrics"),
    ("互动质量评分 0-10", "Interaction quality score 0-10"),
    ("沟通效果评分", "Communication effectiveness score"),
    ("个性化数据表（用于优化推荐和翻译）", "Personalization data table (recommendations and translation)"),
    ("偏好数据（JSON格式）", "Preference data (JSON)"),
    ("数据来源", "Data source"),
    ("置信度 0-1", "Confidence score 0-1"),
    ("使用Statistics", "Usage statistics"),
    ("行为日志表（用于学习用户偏好）", "Behavior log table (preference learning)"),
    ("如果是老人，记录看护者", "Caregiver ID when subject is elder"),
    ("如果是看护者，记录老人", "Elder ID when subject is caregiver"),
    ("行为类型", "Behavior type"),
    ("具体动作", "Specific action"),
    ("行为数据", "Behavior payload"),
    ("行为发生的上下文", "Behavior context"),
    ("结果", "Outcome"),
    ("用户反馈", "User feedback"),
    ("偏好学习表（从行为中学习的偏好）", "Preference learning table"),
    ("如果是关系相关的偏好", "Relationship-scoped preference"),
    ("学习到的偏好", "Learned preferences"),
    ("学习到的偏好数据", "Learned preference payload"),
    ("学习来源", "Learning source"),
    ("来源行为ID列表", "Source behavior IDs"),
    ("置信度", "Confidence score"),
    ("样本数量", "Sample size"),
    ("是否已验证", "Validated flag"),
    ("互动历史表（看护者和老人的互动记录）", "Interaction history table"),
    ("互动类型", "Interaction type"),
    ("互动Content", "Interaction content"),
    ("互动质量", "Interaction quality"),
    ("质量评分", "Quality score"),
    ("满意度评分", "Satisfaction score"),
    ("情绪和反馈", "Mood and feedback"),
    ("活动偏好", "Activity preferences"),
    ("兴趣列表：", "Interests: "),
    ("爱好列表", "Hobbies list"),
    ("喜欢的话题", "Favorite topics"),
    ("个人背景", "Personal background"),
    ("职业经历", "Occupation history"),
    ("家庭信息", "Family info"),
    ("人生故事（重要回忆）", "Life story (key memories)"),
    ("沟通偏好", "Communication preferences"),
    ("偏好的沟通方式", "Preferred communication style"),
    ("活动能力", "Activity capabilities"),
    ("活动能力：", "Capabilities: "),
    ("活动限制", "Activity limitations"),
    ("情绪和性格", "Mood and personality"),
    ("性格特征", "Personality traits"),
    ("任务类型（medication, exercise, appointment, custom）", "Task type (medication, exercise, appointment, custom)"),
    ("截止时间", "Due datetime"),
    ("优先级（low, medium, high）", "Priority (low, medium, high)"),
    ("Reminder settings列表", "Reminder settings list"),
    ("备注", "Notes"),
    ("Task description（可选）", "Task description (optional)"),
    ("优先级（可选）", "Priority (optional)"),
    ("Reminder settings（可选）", "Reminder settings (optional)"),
    ("更新后的任务信息", "Updated task info"),
    ("任务对象", "Task object"),
    ("日期", "Date"),
    ("日程类型（medication, exercise, appointment, activity）", "Schedule type (medication, exercise, appointment, activity)"),
    ("开始时间", "Start time"),
    ("结束时间（可选）", "End time (optional)"),
    ("重复模式（daily, weekly, monthly, custom, none）", "Recurrence (daily, weekly, monthly, custom, none)"),
    ("重复End date (optional)", "Recurrence end date (optional)"),
    ("Custom recurrence pattern（可选）", "Custom recurrence pattern (optional)"),
    ("Description（可选）", "Description (optional)"),
    ("ParticipantsID列表（可选）", "Participant ID list (optional)"),
    ("是否共享（默认True）", "Shared flag (default True)"),
    ("共享给的Family member ID list（可选）", "Family member IDs to share with (optional)"),
    ("地点（可选）", "Location (optional)"),
    ("Relationship ID（可选）", "Relationship ID (optional)"),
    ("创建的日程信息", "Created schedule info"),
    ("日程类型（可选）", "Schedule type (optional)"),
    ("日程列表", "Schedule list"),
    ("开始日期", "Start date"),
    ("结束日期", "End date"),
    ("日历视图数据（Group by date）", "Calendar view data (grouped by date)"),
    ("Title（可选）", "Title (optional)"),
    ("开始时间（可选）", "Start time (optional)"),
    ("结束时间（可选）", "End time (optional)"),
    ("重复模式（可选）", "Recurrence (optional)"),
    ("Participants（可选）", "Participants (optional)"),
    ("是否共享（可选）", "Shared flag (optional)"),
    ("更新后的日程信息", "Updated schedule info"),
    ("将日程对象转换为字典", "Convert schedule to dict"),
    ("Search relevant documents（使用Question和历史上下文）", "Search relevant documents (question + history context)"),
    ("构建上下文Text", "Build context text"),
    ("使用LLM生成Answer", "Generate answer with LLM"),
    ("Auto-categorize change变化", "Auto-categorize change"),
    ("健康Status", "Health status"),
    ("Interests and hobbies卡片", "Interests and hobbies card"),
    ("最近更新", "Recent updates"),
    ("变化类型（created, updated, deleted）", "Change type (created, updated, deleted)"),
    ("Changed-by user ID（可选）", "Changed-by user ID (optional)"),
    ("变化记录", "Change record"),
    (" 性能良好: ", " performing well: "),
    (" 需要改进: ", " needs improvement: "),
    (" 性能较差: ", " poor performance: "),
    (" (阈值: ", " (threshold: "),
    ("Web Vitals 告警: ", "Web Vitals alert: "),
    ("Web Vitals 性能告警", "Web Vitals performance alert"),
    ("指标:", "Metric:"),
    ("当前值:", "Current value:"),
    ("告警级别:", "Alert level:"),
    ("消息:", "Message:"),
    ("时间:", "Time:"),
    ("阈值:", "Thresholds:"),
    ("- 良好: ", "- Good: "),
    ("- 需改进: ", "- Needs improvement: "),
    ("避免使用 SELECT *，只选择需要的列", "Avoid SELECT *; specify only needed columns"),
    ("明确指定需要的列名，减少数据传输", "List required column names to reduce data transfer"),
    ("减少网络传输和内存使用", "Reduces network transfer and memory use"),
    ("查询缺少 LIMIT 子句", "Query missing LIMIT clause"),
    ("添加 LIMIT 子句限制返回行数", "Add LIMIT to cap returned rows"),
    ("防止返回过多数据，提高查询性能", "Prevents oversized result sets and improves performance"),
    ("ORDER BY 可能需要索引支持", "ORDER BY may need index support"),
    ("为 ORDER BY 的列创建索引", "Create index on ORDER BY columns"),
    ("提高排序性能", "Improves sort performance"),
    ("查询包含 ", "Query contains "),
    (" 个 JOIN，可能影响性能", " JOINs; may hurt performance"),
    ("考虑使用子查询或物化视图", "Consider subqueries or materialized views"),
    ("减少 JOIN 复杂度，提高查询速度", "Reduces join complexity and improves speed"),
    ("JOIN 缺少 ON 条件", "JOIN missing ON clause"),
    ("添加适当的 JOIN 条件", "Add appropriate JOIN conditions"),
    ("防止笛卡尔积，提高查询效率", "Avoids cartesian products and improves efficiency"),
    ("WHERE 子句中使用函数可能阻止索引使用", "Functions in WHERE may prevent index use"),
    ("将函数移到应用层或使用计算列", "Move functions to app layer or use computed columns"),
    ("允许使用索引，提高查询性能", "Enables index use and improves query performance"),
    ("LIKE 查询以通配符开头，无法使用索引", "Leading-wildcard LIKE cannot use indexes"),
    ("避免前导通配符，或使用全文搜索", "Avoid leading wildcards or use full-text search"),
    ("允许使用索引，大幅提高查询性能", "Enables indexes and greatly improves performance"),
    ("WHERE 子句中使用 OR 可能影响索引使用", "OR in WHERE may reduce index use"),
    ("考虑使用 UNION 或分别查询", "Consider UNION or separate queries"),
    ("提高索引利用率", "Improves index utilization"),
    (" 的列 ", " columns "),
    (" 创建索引", " create index"),
    (" 创建索引以优化排序", " create index to optimize sorting"),
    (" 创建索引以优化 JOIN", " create index to optimize JOIN"),
    ("发现 ", "Found "),
    (" 个查询缺少 LIMIT，建议添加以限制返回数据量", " queries missing LIMIT; add LIMIT to cap results"),
    (" 个查询使用前导通配符，建议优化以避免全表扫描", " queries with leading wildcards; optimize to avoid full scans"),
    ("建议创建 ", "Recommend creating "),
    (" 个索引以优化查询性能", " indexes to optimize query performance"),
    (" 个查询包含过多 JOIN，建议重构", " queries with too many JOINs; consider refactoring"),
    ("添加了 LIMIT 100 以限制返回行数", "Added LIMIT 100 to cap returned rows"),
    ("将 SELECT * 替换为 SELECT ", "Replaced SELECT * with SELECT "),
    ("（建议明确指定所有需要的列）", " (specify all needed columns explicitly)"),
    ("检测到前导通配符 LIKE，建议移除前导 % 或使用全文搜索", "Leading wildcard LIKE detected; remove leading % or use full-text search"),
    ("将 LIKE '%text' 改为 LIKE 'text%' 或使用全文搜索索引", "Change LIKE '%text' to LIKE 'text%' or use full-text index"),
    ("检测到 OR 条件，建议考虑使用 UNION 以提高索引利用率", "OR condition detected; consider UNION for better index use"),
    ("将 OR 条件拆分为多个查询并使用 UNION 合并", "Split OR into separate queries merged with UNION"),
    ("高优先级优化: ", "High-priority optimization: "),
    ("中优先级优化: ", "Medium-priority optimization: "),
    ("低优先级优化: ", "Low-priority optimization: "),
    ("创建 ", "Create "),
    (" 个高优先级索引可显著提升性能", " high-priority indexes for significant gains"),
    ("查询重写已应用", "Query rewrite applied"),
]
PHRASES.extend(PASS3)

CHINESE_RE = re.compile(r"[\u4e00-\u9fff\u3400-\u4dbf]")


def should_process(path: Path) -> bool:
    if path in SKIP_FILES:
        return False
    if any(part in SKIP_DIRS for part in path.parts):
        return False
    return path.suffix == ".py"


def strip_bilingual_docstring_lines(text: str) -> str:
    """Drop Chinese-only lines in module docstrings when English line exists above."""
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    in_module_doc = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if i == 0 and stripped.startswith('"""'):
            in_module_doc = True
            out.append(line)
            if stripped.count('"""') >= 2 and stripped != '"""':
                in_module_doc = False
            continue
        if in_module_doc:
            if stripped.endswith('"""') and not stripped.startswith('"""'):
                in_module_doc = False
                out.append(line)
                continue
            if stripped.endswith('"""') and stripped == '"""':
                in_module_doc = False
                out.append(line)
                continue
            if CHINESE_RE.search(stripped) and out:
                prev = out[-1].strip()
                if prev and not CHINESE_RE.search(prev) and not prev.startswith("#"):
                    continue
        out.append(line)
    return "".join(out)


def translate_content(text: str) -> str:
    for old, new in MULTILINE:
        text = text.replace(old, new)
    for old, new in sorted(PHRASES, key=lambda x: len(x[0]), reverse=True):
        if old and old in text:
            text = text.replace(old, new)
    text = strip_bilingual_docstring_lines(text)
    return text


def process_file(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    if not CHINESE_RE.search(original):
        return False
    updated = translate_content(original)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def main() -> int:
    targets = [
        BACKEND / "api",
        BACKEND / "middleware",
        BACKEND / "services",
        BACKEND / "dependencies",
        BACKEND / "config",
        BACKEND / "main.py",
        BACKEND / "exceptions.py",
        BACKEND / "utils",
        BACKEND / "models",
        BACKEND / "schemas",
    ]
    modified: list[str] = []
    for target in targets:
        if target.is_file():
            if should_process(target) and process_file(target):
                modified.append(str(target.relative_to(BACKEND)))
        elif target.is_dir():
            for path in sorted(target.rglob("*.py")):
                if should_process(path) and process_file(path):
                    modified.append(str(path.relative_to(BACKEND)))

    print("MODIFIED:")
    for m in modified:
        print(m)
    print(f"\nModified count: {len(modified)}")

    remaining = []
    for path in sorted(BACKEND.rglob("*.py")):
        if not should_process(path):
            continue
        if CHINESE_RE.search(path.read_text(encoding="utf-8")):
            remaining.append(str(path.relative_to(BACKEND)))
    print(f"\nRemaining with Chinese: {len(remaining)}")
    for r in remaining:
        print(r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
